version: '3.9'

services:
  db:
    image: mysql:8.0.32
    container_name: db
    ports:
      - "3306:3306"
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
